### ISSUE TITLE
Need a \veedot

### ISSUE THREAD

**Issue by togo65** [serenity4/SymbolicGA.jl#4]
Julia has a \wedgedot but no \veedot, e.g. to express [geometric  products](http://rigidgeometricalgebra.org/wiki/index.php?title=Geometric_products). Not an issue with your great package but  I would support you if you raised an issue with [Julia Unicode](https://docs.julialang.org/en/v1/manual/unicode-input/)

**Comment by serenity4** [comment]
Done already in https://github.com/JuliaLang/julia/pull/47647 :) this is available on master, I guess we'll need to wait for 1.10 to use it

**Comment by togo65** [comment]
I should have guessed! :1st_place_medal:
